ALTER TABLE "SitePolicy"
  ADD COLUMN "companyCeo" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "companyAddress" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "companyFax" TEXT DEFAULT '',
  ADD COLUMN "businessNumber" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "mailOrderNumber" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "customerCenterTel" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "weekdayHours" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "saturdayHours" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "lunchHours" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "bankName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "bankLogoText" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "bankAccount" TEXT NOT NULL DEFAULT '';
